import { expect, Locator, Page } from '@playwright/test';

export const DASHBOARD_ID = 'opentelemetry-collector';
export const DASHBOARD_TITLE = 'OpenTelemetry Collector';
export const NO_DATA_TEXT = 'No datapoints found.';

/** Names of the `<cr>-collector-monitoring` Services, which is what the dashboard shows as `service`. */
export const COLLECTOR_SERVICE = 'cluster-collector-collector-monitoring';
export const SECOND_COLLECTOR_SERVICE = 'second-collector-monitoring';

export type RowId = 'metrics' | 'traces' | 'resource-usage';

export interface PanelDefinition {
  row: RowId;
  title: string;
  /** Legend entries that the telemetry generated by the Chainsaw test must produce. */
  legends: (namespace: string) => string[];
}

const receiverAccepted = (ns: string) => `otlp/${COLLECTOR_SERVICE}/${ns} accepted/sec`;
const exporterSent = (ns: string) => `debug/${COLLECTOR_SERVICE}/${ns} sent/sec`;
// `otlp/unreachable` is an exporter of the test collector that always fails, see 01-otel-collector.yaml.
const exporterFailed = (ns: string) => `otlp/unreachable/${COLLECTOR_SERVICE}/${ns} failed/sec`;
const perCollector = (ns: string) => [`${COLLECTOR_SERVICE}/${ns}`, `${SECOND_COLLECTOR_SERVICE}/${ns}`];

/**
 * The nine panels of the dashboard (three rows of three) with the legend entries that must be present.
 *
 * Not asserted: the "refused" series (only exist after a refusal) and the "dropped" series of the processor
 * panels, which cannot exist at all because the memory limiter processor has no dropped metric.
 */
export const PANELS: PanelDefinition[] = [
  {
    row: 'metrics',
    title: 'Metrics Accepted vs Refused Received / second',
    legends: (ns) => [receiverAccepted(ns)],
  },
  {
    row: 'metrics',
    title: 'Metrics Exported vs Failed / second',
    legends: (ns) => [exporterSent(ns), exporterFailed(ns)],
  },
  {
    row: 'metrics',
    title: 'Processor Metrics accepted, dropped, refused / second',
    legends: () => ['memory_limiter | accepted'],
  },
  {
    row: 'traces',
    title: 'Spans Accepted vs Refused Received / second',
    legends: (ns) => [receiverAccepted(ns)],
  },
  {
    row: 'traces',
    title: 'Spans Exported vs Failed / second',
    legends: (ns) => [exporterSent(ns), exporterFailed(ns)],
  },
  {
    row: 'traces',
    title: 'Processor Spans accepted, dropped, refused / second',
    legends: (ns) => [`memory_limiter/${COLLECTOR_SERVICE}/${ns} | accepted`],
  },
  {
    row: 'resource-usage',
    title: 'Total physical memory (resident set size)',
    legends: perCollector,
  },
  {
    row: 'resource-usage',
    title: 'Bytes of allocated heap objects',
    legends: perCollector,
  },
  {
    row: 'resource-usage',
    title: 'Total CPU user and system time in percentage',
    legends: (ns) => perCollector(ns).map((legend) => `CPU usage ${legend}`),
  },
];

/** Dashboard variables that are always populated for the generated telemetry. */
export const VARIABLES = [
  'span exporter',
  'metric exporter',
  'metric receiver',
  'span receiver',
  'span processor',
  'metric processor',
  'namespace',
  'collector instance',
] as const;
export type VariableName = (typeof VARIABLES)[number];

export class CollectorDashboardPage {
  constructor(readonly page: Page) {}

  /**
   * Open the dashboard directly.
   *
   * The dashboard is only offered for "All Projects": with a concrete project the console lists just the
   * namespace-scoped dashboards and replaces this one, so the project is always pinned here.
   */
  async open(variables: Partial<Record<VariableName, string>> = {}): Promise<void> {
    const params = new URLSearchParams({ 'project-dropdown-value': '#ALL_NS#', ...variables });
    await this.page.goto(`/monitoring/dashboards/${DASHBOARD_ID}?${params}`, { waitUntil: 'domcontentloaded' });
    await this.expectDashboardSelected();
  }

  /** The dashboard picker: a typeahead select, the selected dashboard is the value of its input. */
  get dashboardPicker(): Locator {
    return this.page.locator('[data-test="dashboard-dropdown"]');
  }

  async expectDashboardSelected(): Promise<void> {
    await expect(this.dashboardPicker.getByRole('combobox')).toHaveValue(DASHBOARD_TITLE);
  }

  row(id: RowId): Locator {
    return this.page.locator(`[data-test-id="panel-${id}"]`);
  }

  /** `data-test` of a panel is the lower-cased title with dashes for spaces, plus `-chart`. */
  panel(definition: PanelDefinition): Locator {
    const slug = definition.title.toLowerCase().replace(/\s+/g, '-');
    return this.row(definition.row).locator(`[data-test="${slug}-chart"]`);
  }

  /**
   * Panels are rendered lazily, when they scroll into view. Scroll to the panel and wait until it either
   * shows a legend/axis or reports "No datapoints found." (a panel without a rendered chart is not done).
   */
  async reveal(definition: PanelDefinition): Promise<Locator> {
    const panel = this.panel(definition);
    await panel.scrollIntoViewIfNeeded();
    await expect(panel).toContainText(definition.title);
    return panel;
  }

  variable(name: VariableName): Locator {
    return this.page.locator(`[data-test="${name}-dropdown"]`);
  }

  /** Options of a variable dropdown (including "All"). */
  async variableOptions(name: VariableName): Promise<string[]> {
    const toggle = this.variable(name).getByRole('button');
    // click() scrolls into view and retries on DOM detachment, unlike scrollIntoViewIfNeeded().
    await toggle.click();
    const options = this.page.getByRole('option');
    await expect(options.first()).toBeVisible();
    const texts = (await options.allInnerTexts()).map((text) => text.trim());
    await this.page.keyboard.press('Escape');
    return texts;
  }

  async selectVariable(name: VariableName, option: string): Promise<void> {
    const toggle = this.variable(name).getByRole('button');
    // click() scrolls into view and retries on DOM detachment, unlike scrollIntoViewIfNeeded().
    await toggle.click();
    await this.page.getByRole('option', { name: option, exact: true }).click();
  }

  /** Assert that a panel is drawn with all the given legend entries and without the "no data" message. */
  async expectPanelHasData(definition: PanelDefinition, namespace: string): Promise<void> {
    const panel = await this.reveal(definition);
    await expect(panel).not.toContainText(NO_DATA_TEXT);
    for (const legend of definition.legends(namespace)) {
      await expect(panel).toContainText(legend);
    }
  }
}
