#!/bin/bash
# This script checks the OpenTelemetry collector pod for evidence that the
# span_metrics connector derived R.E.D metrics from incoming spans, including
# that the aggregated call count actually matches the number of spans sent.

LABEL_SELECTOR="app.kubernetes.io/component=opentelemetry-collector"
NAMESPACE=$NAMESPACE
# Number of traces generated by generate-telemetry-data.yaml - each trace
# produces one "okey-dokey-0" (server) span, so the calls metric for it
# should aggregate to this count.
EXPECTED_CALLS=5

SEARCH_STRINGS=(
  "Name: traces.span.metrics.calls"
  "Name: traces.span.metrics.duration"
  "service.name: Str(spanmetrics-test)"
)

for attempt in $(seq 1 30); do
    PODS=($(kubectl -n $NAMESPACE get pods -l $LABEL_SELECTOR -o jsonpath='{.items[*].metadata.name}'))

    if [ ${#PODS[@]} -eq 0 ]; then
        echo "Attempt $attempt: no pods found with label $LABEL_SELECTOR in namespace $NAMESPACE, retrying in 10s..."
        sleep 10
        continue
    fi

    POD=${PODS[0]}
    LOGS=$(kubectl -n $NAMESPACE logs $POD --tail=-1)
    ALL_FOUND=true

    for STRING in "${SEARCH_STRINGS[@]}"; do
        if ! echo "$LOGS" | grep -qF -- "$STRING"; then
            ALL_FOUND=false
            break
        fi
    done

    # Also confirm the calls metric actually aggregated to the expected
    # count, not just that a metric with that name was emitted.
    CALLS_BLOCK=$(echo "$LOGS" | grep -A 15 -- "Name: traces.span.metrics.calls")
    if ! echo "$CALLS_BLOCK" | grep -qF -- "Value: $EXPECTED_CALLS"; then
        ALL_FOUND=false
    fi

    if $ALL_FOUND; then
        for STRING in "${SEARCH_STRINGS[@]}"; do
            echo "\"$STRING\" found in $POD"
        done
        echo "\"Value: $EXPECTED_CALLS\" found near a traces.span.metrics.calls metric in $POD"
        echo "Log search completed for all defined strings in pod $POD."
        exit 0
    fi

    if (( attempt < 30 )); then
        echo "Attempt $attempt: not all defined strings/values found yet in pod $POD, retrying in 10s..."
        sleep 10
    fi
done

echo "Timed out waiting for all defined strings/values in pod $POD"
exit 1
